sudo: false

language: go

go:
  - "1.10"

git:
  depth: 1

notifications:
  email: false

before_install:
  # For testing of creating dbs on the Desktop
  - mkdir /home/travis/Desktop
  - go get github.com/mattn/goveralls

install:
- curl -sLOf https://raw.githubusercontent.com/rafecolton/fmtpolice/master/coverage
- go get -u code.google.com/p/go.tools/cmd/cover || go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/axw/gocov/gocov github.com/mattn/goveralls

script:
- go test ./...
- bash coverage
- ${GOPATH%%:*}/bin/goveralls -coverprofile=gover.coverprofile