sudo: false

language: go

go:
  - "1.10"

git:
  depth: 1

notifications:
  email: false

before_install:
  # For testing of creating dbs on the Desktop
  - mkdir /home/travis/Desktop
  - go get github.com/mattn/goveralls

install: true

script:
  # Run tests
  - $GOPATH/bin/goveralls -service=travis-ci